### ISSUE TITLE
retain_graph = True  vs create_graph = True? 

### ISSUE THREAD

**Issue by goodman1204** [ChandlerBang/pytorch-gnn-meta-attack#2]
Hi, 

In the two ** inner_train** functions in Class **Metattack** and **MetaApprox**, to calculate the gradients of weights, the parameters for the **autograd.grad** function are different, can you kindly explain the reasons behind this? 

line 181 in metattack.py

> weight_grads = torch.autograd.grad(loss_labeled, self.weights, create_graph=True)

line 327 in metattack.py
> self.grad_sum += torch.autograd.grad(attack_loss, self.adj_changes, retain_graph=True)[0]

**Comment by ChandlerBang** [comment]
Hi, 

`Metattack` requires to store the computation graph of the whole tracjectory so we need to set `creat_graph` to `True`. By contrast, `MetaApprox` discards the dependency between model parameters  at different steps; so we set `create_graph` to `False`.

**Comment by goodman1204** [comment]
Thanks for your explanation. It is clear now.
